import React from "react";
import Head from "next/head";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { GithubIcon } from "@/components/Icons";
import Image from "next/image";
import Examgenie from "../../public/images/projects/Exam_genie.PNG";
import { motion } from "framer-motion";

const FramerImage = motion(Image);

const FeatureProject = ({ type, title, summary, img, link, github }) => {
  return (
    <article
      className="w-full flex items-center justify-between 
    rounded-3xl border border-solid border-dark bg-light shadow-2xl p-12 relative rounded-br-2xl  dark:bg-dark dark:border-light"
    >
      <div
        className="absolute top-0 -right-3 left-0 -z-10 w-[101%]  h-[103%] rounded-[3rem] bg-dark  dark:bg-light
      rounded-br-3xl"
      />

      <Link
        href={link}
        target="_blank"
        className="w-1/2 cursor-pointer overflow-hidden rounded-lg"
      >
        <FramerImage src={img} alt={title} className="w-full h-auto"
        whileHover={{scale:1.05}}
        transition={{duration:0.2}} 
        priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"/>
      </Link>
      <div className="w-1/2 flex flex-col items-start justify-between pl-6">
        <span className="text-blue-700 font-medium text-xl dark:text-blue-400">{type}</span>
        <Link
          href={link}
          target="_blank"
          className="hover:underline underline-offset-2"
        >
          <h2 className="my-2 w-full text-left text-4xl font-bold dark:text-light">{title}</h2>
        </Link>
        <p className="my-2 font-medium text-dark dark:text-light">{summary}</p>
        <div className="mt-2 flex items-center ">
          <Link href={github} target="_blank" className="w-10">
            <GithubIcon />
          </Link>
          <Link
            href={link}
            target="_blank"
            className="ml-4 rounded-lg bg-dark text-light
          p-2 px-6 text-lg font-semibold dark:bg-light dark:text-dark
          "
          >
            Visit Project
          </Link>
        </div>
      </div>
    </article>
  );
};

const Project = ({ title, type, img, link, github }) => {
  return (
    <article
      className="w-full flex flex-col items-center justify-center rounded-2xl 
    border border-solid border-dark bg-light p-6 relative dark:bg-dark dark:border-light"
    >
      <div
        className="absolute top-0 -right-3 left-0 -z-10 w-[102%]  h-[103%] rounded-[2.9rem] bg-dark 
      rounded-br-3xl dark:bg-light"
      />
      <Link
        href={link}
        target="_blank"
        className="w-full cursor-pointer overflow-hidden rounded-lg"
      >
        <FramerImage src={img} alt={title} className="w-full h-auto" 
        whileHover={{scale:1.05}}
        transition={{duration:0.2}}/>
      </Link>
      <div className="w-full flex flex-col items-start justify-between mt-4">
        <span className="text-blue-700 font-medium text-xl dark:text-blue-400">{type}</span>
        <Link
          href={link}
          target="_blank"
          className="hover:underline underline-offset-2"
        >
          <h2 className="my-2 w-full text-left text-3xl font-bold">{title}</h2>
        </Link>

        <div className=" w-full mt-2 flex items-center justify-between ">
          <Link
            href={link}
            target="_blank"
            className="text-lg font-semibold underline"
          >
            Visit
          </Link>
          <Link href={github} target="_blank" className="w-8 ">
            <GithubIcon />
          </Link>
        </div>
      </div>
    </article>
  );
};
const projects = () => {
  return (
    <>
      <Head>
        <title>Fabian Morales | Projects Page</title>
        <meta
          name="description"
          content="This page is all projects of full stack developer Fabian Morales"
        />
      </Head>
      <main className="w-full mb-16 flex flex-col items-center justify-center dark:text-light">
        <Layout className="pt-16">
          <AnimatedText
            text="The limits of knowledge are as far as imagination can reach."
            className="mb-40"
          />

          <div className="grid grid-cols-12 gap-24 gap-y-36">
            <div className="col-span-12">
              <FeatureProject
                title="Exam Genie"
                img={Examgenie}
                summary="This project is a question generator for the preparation of different types of tests, the questions are generated by artificial intelligence as well as the feedback of the correct answer, has within its components a section for challenge or game to study in group, the application saves the history of the exams for future reference."
                link="https://github.com/femorales7/exam-genie"
                github="https://github.com/femorales7/exam-genie"
                type="Featured Project"
              />
            </div>
            <div className="col-span-6">
              <Project
                title="Exam Genie"
                img={Examgenie}
                summary="This project is a question generator for the preparation of different types of tests, the questions are generated by artificial intelligence as well as the feedback of the correct answer, has within its components a section for challenge or game to study in group, the application saves the history of the exams for future reference."
                link="https://github.com/femorales7/exam-genie"
                github="https://github.com/femorales7/exam-genie"
                type="Featured Project"
              />
            </div>
            <div className="col-span-6">
              <Project
                title="Exam Genie"
                img={Examgenie}
                summary="This project is a question generator for the preparation of different types of tests, the questions are generated by artificial intelligence as well as the feedback of the correct answer, has within its components a section for challenge or game to study in group, the application saves the history of the exams for future reference."
                link="https://github.com/femorales7/exam-genie"
                github="https://github.com/femorales7/exam-genie"
                type="Featured Project"
              />
            </div>

            <div className="col-span-12">
            <FeatureProject
                title="Exam Genie"
                img={Examgenie}
                summary="This project is a question generator for the preparation of different types of tests, the questions are generated by artificial intelligence as well as the feedback of the correct answer, has within its components a section for challenge or game to study in group, the application saves the history of the exams for future reference."
                link="https://github.com/femorales7/exam-genie"
                github="https://github.com/femorales7/exam-genie"
                type="Featured Project"
              />
            </div>
            <div className="col-span-6">
              <Project
                title="Exam Genie"
                img={Examgenie}
                summary="This project is a question generator for the preparation of different types of tests, the questions are generated by artificial intelligence as well as the feedback of the correct answer, has within its components a section for challenge or game to study in group, the application saves the history of the exams for future reference."
                link="https://github.com/femorales7/exam-genie"
                github="https://github.com/femorales7/exam-genie"
                type="Featured Project"
              />
            </div>
            <div className="col-span-6">
              <Project
                title="Exam Genie"
                img={Examgenie}
                summary="This project is a question generator for the preparation of different types of tests, the questions are generated by artificial intelligence as well as the feedback of the correct answer, has within its components a section for challenge or game to study in group, the application saves the history of the exams for future reference."
                link="https://github.com/femorales7/exam-genie"
                github="https://github.com/femorales7/exam-genie"
                type="Featured Project"
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default projects;
